language: perl
sudo: false
perl:
    - "5.22"
    - "5.14"
    - "5.10"
cache:
    directories:
        - local
before_install:
    - cpanm Carton
install:
    - carton install
script:
    - carton exec -- prove -lrv t
